[workspace]
members = [
  "moebius-derive",

  "moebius/cli",
  "simple_program/cli",
  "uniswap_oracle/cli",

  "moebius/program",
  "simple_program/program",
  "uniswap_oracle/program",

  "reporter",

  "another_program/program",
]
